version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rodrigohenrique07/portfolio-rodrigo
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3334:3334'
    command: npm run dev -- --host 0.0.0.0
    mem_limit: 1g
